development: &default
  adapter: postgresql
  database: sv_work
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: sv_work_test

production:
  <<: *default
  database: sv_work_production
